site_name: Formlaez
site_url: https://formlaez.com/
markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
theme:
  name: 'material'
  logo: https://formlaez.com/wp-content/uploads/2021/07/formlaez.svg
  language: vi
  font:
    text: Roboto
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Trang chủ: index.md
  - Hướng dẫn:
    - Giới thiệu chung: guide/getting-started.md
    - Quản lý tổ chức: guide/account.md
    - Quản lý gói dịch vụ: guide/billing-payment.md
    - Quản lý không gian làm việc: guide/workspace.md
    - Quản lý thư mục: guide/folder.md
    - Biểu mẫu:
      - Cấu hình biểu mẫu: guide/form-config.md
      - Cài đặt biểu mẫu: guide/form-settings.md
      - Cấu hình in ấn: guide/form-printing.md
      - Chia sẻ biểu mẫu: guide/form-sharing.md
      - Danh sách phản hồi: guide/form-responses.md
      - Cấu hình Webhook: guide/form-webhook.md